examples:
                routes:
                  value:
                    - routeId: 1
                      deliveryId: 101
                      source: "Warehouse A"
                      destination: "Customer B"
                      routeOrder: "First"
                      estimatedTime: "2 hours"
                      distance: 15.5
                      trafficConditions: "Moderate"
                      expectedDelay: "30 minutes"
                    - routeId: 2
                      deliveryId: 102
                      source: "Warehouse B"
                      destination: "Customer C"
                      routeOrder: "Second"
                      estimatedTime: "3 hours"
                      distance: 25.0
                      trafficConditions: "Heavy"
                      expectedDelay: "1 hour"
